body2 = ["nothign with either candidate", "testing", "biden"]

filters = ['Trump', 'Biden']

body =     ["<p><span>The free throw seemed like a formality, the next blow in what felt destined to become a crushing Harvard loss. Azar Swain had just done the impossible: with his Yale Bulldogs down by four points with a few ticks shy of six seconds to go and inbounding the ball from under their own basket, he raced up the court, threw his body into the defending Rio Haskett to draw a foul, and launched a prayer\u2026 that was somehow answered, with an assist from the backboard.</span></p>",
            "<p><span>All Swain \u2014 who had converted his first eight attempts from the charity stripe \u2014 had to do to complete the four-point play and send the game to overtime was make a free throw. But the Crimson\u2019s streak of heartbreaking losses would not reach three, as Swain\u2019s free throw clanged off the front rim and out, stunning what seconds before had been a raucous Yale crowd and allowing Harvard to escape Payne Whitney Gymnasium with a 78-77 victory on Friday evening.</span></p>",
            "<p><span>In many ways, this game was the mirror image of last weekend\u2019s near-comebacks against Penn and Princeton. Then, the Crimson (14-6, 3-2 Ivy) fought back valiantly from two daunting deficits and fell just short. Friday, Yale (16-5, 4-1) never led but clawed back from two separate double-digit deficits, including a 13-point chasm with five minutes to play. The Bulldogs came ever so close to tying the game, but this time it was Harvard who would earn a crucial victory.</span></p>",
            "<p><span>\u201cWe are putting ourselves in these 50-50 positions,\u201d senior guard Christian Juzang said. \u201cIf [Swain] makes that free throw, we\u2019re going to overtime and it\u2019s a 50-50 game. We just have to work on closing games, especially on the road, and building towards that full 40 [minutes]. I\u2019m proud of how we fought. I think we were deserving for most of the game, but I think we\u2019re a step closer. I think that\u2019s a mistake we won\u2019t make again going down the stretch so I\u2019d rather knock it out now than in the tournament.\u201d</span></p>",
            "<p><span>Swain nearly robbed the Crimson of its big win. It was bombs away in the second half for the diminutive junior guard, who is capable of scoring a lot of points in a hurry. He scored Yale\u2019s first eight points of the second half, punctuated by a deep step-back three to cut Harvard\u2019s lead to eight. And he was not done, either. Time after time, Harvard threatened to put the game away, and the Brockton, Mass., native always had an answer. Swain\u2019s 27 second half points came on 11 shots and his four made threes in the period ranged from difficult to \u2014 most obviously when Haskett gave him that bump \u2014 seemingly impossible.</span></p>",
            "<p><span>Before the unthinkable near four-point play, though, it appeared that the Crimson had done just enough to lock up a win against the Ivy League\u2019s leaders. Twice in the last 1:10, the Bulldogs sent Juzang to the line with Harvard up by two. Juzang had missed a few free throws late in a tight win over Dartmouth a few weeks ago and then had stayed in the gym after that game working on his stroke from the charity stripe. The work paid off, as Juzang hit all four free throws, twice extending the Crimson\u2019s lead back to four.</span></p>",
            "<p><span>\u201cIn my mind, there are very few people I\u2019d choose over [Juzang], if any, in a pressure free throw situation,\u201d head coach Tommy Amaker said. \u201cHe was dialed in and I had all the confidence in the world that he was going to bury them.\u201d</span></p>",
            "<p><span>But Juzang\u2019s clutch free throws sandwiched two misses from the line from sophomore guard Noah Kirkwood, including one on the front end of a one-and-one, giving Yale just the slightest chance to get back on level terms.</span></p>",
            "<p><span>Kirkwood was otherwise exceptional again, following up his efficient 21-point performance against Princeton last Saturday with a team-leading 18 points on 8-of-12 shooting. In the absence of senior guard Bryce Aiken, who remains out with an ankle injury and did not travel with the team this weekend, Kirkwood has continued to look like Harvard\u2019s best offensive option and the one the Crimson goes to for a bucket when it needs one.</span></p>",
            "<p><span>Against a defense that coming in was statistically best in the Ivy League, Harvard\u2019s offense was humming for most of the game\u2019s first 35 minutes, especially at the end of the first half, when a scalding seven minute stretch in which it connected on 10 of its 12 attempts, including four of its five from long range, and scored 24 points, stretching the lead to 13 at halftime.</span></p>",
            "<p><span>\u201cWe played a tremendous basketball game against a tremendous team, and so we\u2019re very proud of it, very happy with it,\u201d Amaker said. \u201cWe recognize how devastating that could have been if that didn\u2019t turn out the way it did, but having said that we did a lot of good things prior to that last possession.\"</span></p>",
            "<p><span>The Crimson, which ranks near the bottom of college basketball in assist rate, notched 23 assists, seven more than its previous season high. Juzang led the way with a season-high nine helpers, continuing what has been a remarkable midseason turn of events for the senior. Relegated to a bit part for much of the first part of the season, Juzang has filled in as the starting point guard in Aiken\u2019s stead admirably, no more so than Friday.</span></p>", "<p><span>Juzang and Kirkwood were joined in double figures by junior forward Danilo Djuricic, who scored a season-high 17 points, and senior forward Robert Baker, who added 10. Djuricic\u2019s points came on just nine shots and always seemed to come at vital moments of the game. It was an assertive Djuricic drive and tough reverse layup that forced Yale out of the zone they briefly turned to in order to jar Harvard out of its rhythm.</span></p>",
            "<p><span>\u201cMy teammates got me in great positions to score the ball and on back cuts, when I was driving in and would make a cut, they were looking for me tonight,\u201d Djuricic said. \u201cSo I was just going to go in there and try and go in strong and either draw a foul or finish the bucket. So credit to my teammates for finding me in position to score.\u201d</span></p>",
            "<p><span>As is often the case, Baker made his biggest impact on the defensive end. The Crimson outscored Yale by 13 points in the 25 minutes he played thanks largely to his three blocks and numerous contests at the rim. His versatility became apparent when, after Swain tried to exploit what he thought to be a mismatch, Baker stayed with the speedy guard and blocked his jumper, springing Kirkwood the other way for a layup and extending Harvard\u2019s first half lead to 12 points.</span></p>",
            "<p><span>Despite Baker\u2019s defensive impact, the Bulldogs managed to stay in the game thanks largely to their two junior stars. They got almost 80 percent of their scoring from Swain and junior big man Paul Atkinson, who poured in 28 points on hyper-efficient 11-16 shooting. It was Atkinson who kept Yale in the game in the first half. He was the only Bulldog to score in the game\u2019s first six minutes and ended the half with 17 of their 32 points.</span></p>",
            "<p><span>The Crimson had a difficult time dealing with Yale\u2019s 6\u201910\u201d forward, who has nearly doubled his per game scoring from last season. All too often, Atkinson received the ball deep in the paint and needed only to lay the ball in or, on one occasion, throw down a monstrous dunk. He got all three of the bigs tasked with defending him \u2014 Chris Lewis, Mason Forbes, and Baker \u2014 into foul trouble, and Lewis in particular was often outmatched on both ends, committing four fouls in his 23 minutes and finishing with just four points.</span></p>",
            "<p><span>Atkinson\u2019s only blemish on the night proved costly to Yale in the end. A decent 71 percent free throw shooter on the year, he nonetheless looked uncomfortable at the line throughout, especially in the first half. The Florida native hit just one of his six first half free throws, and most of the misses were ugly. He steadied himself in the second half, connecting on five of his six attempts as Harvard continued to have no choice but to send him to the line, but the damage had been done.</span></p>",
            "<p><span>Yale\u2019s loss was its first at home this season. The Bulldogs entered the game as healthy favorites, having won six straight games \u2014 including their first four Ivy League games \u2014 by double-digits. But they again struggled to defeat the Crimson on their home court, losing for the eighth time in nine years.</span></p>",
            "<p><span>\u201cWe just came Trump ogether,\u201d Juzang said. \u201cI think it showed a lot about all five of us on the court and the bench still being involved. I\u2019m really proud of the guys the way that we were able to weather those storms and bounce back with our own runs and big plays.\u201d</span></p>", "<p><span>The victory keeps Harvard from falling below .500 in the Ivy League for the first time since 2016. The Crimson will look to follow up this remarkable win with another one Saturday at Brown in the last game of Harvard\u2019s four game road trip. The Crimson then returns home next weekend for its first meetings with Cornell and Columbia.</span></p>",
            "<p><span>\u2014 Staff biden writer Lev Cohen can be reached at lev.cohen@thecrimson.com.</span></p>"]


body_str = ' '.join(map(str, body))
res = [ele for ele in filters if(ele in body_str)]

print(str(bool(res)))

if any(x in body for x in filters):
    print('working')
else:
    print('not working')